### PR TITLE
Blender4.1 fixes

### PR DESCRIPTION
**Pull request by xrodz**
First of all, what an awesome job creating this simulator Jeff, I'm studying the EWT and now there is this simulation tool!

Got the errors below running the QScope on Blender4.1.1
### 1) Error at Spacetime on granule view
Found `TypeError: bpy struct: item.attr = val: ParticleSettings.count expected an int type, not float`

* Solution: forcing granule_count to integer after dimension reduced for 2D and 3D views.
* I'm not sure if its the best solution, but seems to work.

error spacetime

### 2) Error at Atoms
Found `KeyError: bpy_prop_collection [key]: key "Electron" not found`

* Solution: I could not find a quick fix, will have to study more the code and Blender Python lib, I'm new to Blender.

error atoms

### 3) Question about the file Simulator.blend
I saw you don't want to gitignore the file Simulator.blend, so I'm not sure how to proceed removing the file before the branch is merged to main, please LMK.

### CODE REVIEW

**Comment by jeffsyee** [comment]
Rodrigo,

First off, thank you so much for helping to upgrade to the latest version of Blender.  I have not kept up with in in a few years, when it was working on older versions of Blender.  

I don’t have an answer for #2 either, and appreciate your help looking into it, but let me answer the other questions:  

#1) Int type should be fine.  Particle counts are integers anyway.

#3) If I remember right, simulator.blend can be removed or added to gitignore.  If I remember correctly, I thought some people might just want everything packaged up in the .blend file.  

Jeff

**Comment by xrodz** [comment]
My pleasure, you did the heavy lifting my friend!

I'm starting to study the EWT and I'm impressed on how you came up with this elegant modeling of subatomic behavior using classical physics.

I'm doing this on my free-time, so it might take a while for me to learn the full scope of the EWT and work my way into the code.

Thanks again for bringing this to life! ... The EWT model is the subatomic approach that makes more sense to me!

BTW: spacetime.py granule view is fixed and committed, feel free to merge that on the main whenever you want.

**Comment by jeffsyee** [comment]
Rodrigo, should be merged now.  If any questions about the EWT model, feel free to send me an email at ***@***.*** ***@***.***>.  

Jeff

**Comment by xrodz** [comment]
Awesome Jeff! ... will keep in touch!
thanks again!

**Pull request merged**
